Add name
leosartaj/learn-git pull request #27
Opened 2016-12-14 04:17 UTC by Vaibhavdixit02

2016-12-14 14:11 UTC, leosartaj requested changes

2016-12-14 14:11 UTC, leosartaj commented on README.md
> -* Harshit [iamharshit] (https://github.com/iamharshit)
Why was this removed?

2016-12-14 14:15 UTC, Vaibhavdixit02 commented on README.md
> -* Harshit [iamharshit] (https://github.com/iamharshit)
Must have been by mistake. Did not pay attention . Sorry.

2016-12-14 14:46 UTC, leosartaj commented on README.md
> -* Harshit [iamharshit] (https://github.com/iamharshit)
No, I guess his name was never added to AUTHORS.md. If you add there and run the script, it should be good.

2016-12-14 15:02 UTC, Vaibhavdixit02 commented on README.md
> -* Harshit [iamharshit] (https://github.com/iamharshit)
I did sir, but there seems to be some error and it is saying that the Travis CI build failed.

2016-12-14 15:24 UTC, leosartaj approved these changes

2016-12-14 15:25 UTC, leosartaj commented on README.md
> +* Harshit  [iamharshit](https://github.com/iamharshit)
Don't add manually run the script.

2016-12-16 23:02 UTC, leosartaj commented on README.md
> +* Harshit  [iamharshit](https://github.com/iamharshit)
Just replace `Harshit  [iamharshit](https://github.com/iamharshit)` with 
`Harshit [iamharshit](https://github.com/iamharshit)`

2016-12-21 07:22 UTC, Vaibhavdixit02 commented on README.md
> +* Harshit  [iamharshit](https://github.com/iamharshit)
Done.

2016-12-21 07:34 UTC, merged

2016-12-21 07:34 UTC, leosartaj commented
Thanks! It's in.